packaging_format = 2

id = "bloat"
name = "Bloat"
description.en = "Web client for Pleroma, Mitra and other Fediverse connected apps"
description.fr = "Client web pour Pleroma, MItra et d'autres applications connectées au Fediverse"

version = "1.0~ynh1"

maintainers = ["Papa Dragon"]

[upstream]
license = "Unlicense" # you can see the available licenses identifiers list here: https://spdx.org/licenses/
admindoc = "https://git.freesoftwareextremist.com/bloat/tree/README"
code = "https://git.freesoftwareextremist.com/bloat/"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = ["amd64"]
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://git.freesoftwareextremist.com/bloat/snapshot/bloat-68d7acc2f7266c47001445229ff235546c8c71b4.zip"
        sha256 = "0ef6c47baf1decfed1043850ee3fa5bd7bf2c849ce7621ff4fafc0e91af06f91"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    