#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# BUILD APP
#=================================================
#REMOVEME? ynh_go_install

pushd $install_dir
    ynh_exec_as_app make
popd

ynh_replace --match="listen_address=127\.0\.0\.1:8080" --replace="listen_address=127\.0\.0\.1:$port" --file=$install_dir/bloat.gen.conf
ynh_replace --match="client_website=http:\/\/127\.0\.0\.1:8080" --replace="client_website=$domain$path" --file=$install_dir/bloat.gen.conf
ynh_replace --match="\/usr\/local\/share\/bloat\/" --replace="" --file=$install_dir/bloat.gen.conf

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Web client for Pleroma" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="^.*auth\.php.*failed login attempt.*from IP <HOST>.*$"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
