#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

#=================================================
# BUILD APP
#=================================================
ynh_go_install

pushd $install_dir
    ynh_exec_as_app make
popd

ynh_replace --match="listen_address=127\.0\.0\.1:8080" --replace="listen_address=127\.0\.0\.1:$port" --file=$install_dir/bloat.gen.conf
ynh_replace --match="client_website=http:\/\/127\.0\.0\.1:8080" --replace="client_website=$domain$path" --file=$install_dir/bloat.gen.conf
ynh_replace --match="\/usr\/local\/share\/bloat\/" --replace="" --file=$install_dir/bloat.gen.conf

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="$install_dir/bloat.gen.conf" --destination="/etc/$app.conf"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="Bloat - A web client for Pleroma" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="^.*auth\.php.*failed login attempt.*from IP <HOST>.*$"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
